name: event_app
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_native_splash: ^2.4.4
  google_fonts: ^6.2.1
  flutter_localizations:
    sdk: flutter
  intl: any
  provider: ^6.1.4
  flutter_switch: ^0.3.2
  toggle_switch: ^2.3.0
  introduction_screen: ^3.1.17
  firebase_core: ^3.13.0
  cloud_firestore: ^5.6.7
  fluttertoast: ^8.2.12
  google_maps_flutter: ^2.12.1
  firebase_auth: ^5.5.3
  geocoding: ^2.1.0

 

flutter_native_splash:
  color: "#ffffff"
  color_dark: "#101127"
  image_dark: assets/images/Logo.png
  image: assets/images/Logo.png
  android_12:
    color: "#ffffff"
    color_dark: "#101127"
    image_dark: "assets/images/Logo.png"
    image: "assets/images/Logo.png"
    icon_background_color: "#ffffff"
    icon_background_color_dark: "#101127"

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
 

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/images/
    - assets/images/icons/
    - assets/style/


