// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAvpwjeR5FqbAvcuBnkdbSPVX_tngCY28k',
    appId: '1:935602342556:web:9b8a249e1e1d42f37e7b59',
    messagingSenderId: '935602342556',
    projectId: 'event-app-97784',
    authDomain: 'event-app-97784.firebaseapp.com',
    storageBucket: 'event-app-97784.firebasestorage.app',
    measurementId: 'G-V12ZNQVLT1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBwX_3-ovs-TDGymk2qL6b-9TowUjJ4a-s',
    appId: '1:935602342556:android:996da39275aab9597e7b59',
    messagingSenderId: '935602342556',
    projectId: 'event-app-97784',
    storageBucket: 'event-app-97784.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAxp58QMVYr2on6F-rFOI5bP_R3Pc5yjUY',
    appId: '1:935602342556:ios:e8a8247025cec83f7e7b59',
    messagingSenderId: '935602342556',
    projectId: 'event-app-97784',
    storageBucket: 'event-app-97784.firebasestorage.app',
    iosBundleId: 'com.example.eventApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAxp58QMVYr2on6F-rFOI5bP_R3Pc5yjUY',
    appId: '1:935602342556:ios:e8a8247025cec83f7e7b59',
    messagingSenderId: '935602342556',
    projectId: 'event-app-97784',
    storageBucket: 'event-app-97784.firebasestorage.app',
    iosBundleId: 'com.example.eventApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAvpwjeR5FqbAvcuBnkdbSPVX_tngCY28k',
    appId: '1:935602342556:web:0d9f2d639bb7ed9a7e7b59',
    messagingSenderId: '935602342556',
    projectId: 'event-app-97784',
    authDomain: 'event-app-97784.firebaseapp.com',
    storageBucket: 'event-app-97784.firebasestorage.app',
    measurementId: 'G-YB187NYE6D',
  );

}